export const INSPECTION_SECTIONS = [
    {
        id: "motor",
        label: "Motor",
        items: [
            { id: "m1", label: "Nivel y estado de aceite (limpieza/viscosidad)" },
            { id: "m2", label: "Fugas de aceite en tapa de punterías" },
            { id: "m3", label: "Fugas de aceite en retén de cigüeñal" },
            { id: "m4", label: "Nivel y estado del anticongelante" },
            { id: "m5", label: "Fugas de refrigerante en mangueras y radiador" },
            { id: "m6", label: "Estado de la banda de accesorios (grietas)" },
            { id: "m7", label: "Ruidos de punterías o válvulas en frío" },
            { id: "m8", label: "Presencia de humo azul o negro en el escape" },
            { id: "m9", label: "Estado de soportes de motor" },
            { id: "m10", label: "Limpieza del cuerpo de aceleración" },
            { id: "m11", label: "Estado de las bujías (si es visible)" },
            { id: "m12", label: "Estado de los cables de bujías/bobinas" },
            { id: "m13", label: "Filtro de aire (limpieza)" },
            { id: "m14", label: "Estado de la batería (terminales sin sulfato)" },
            { id: "m15", label: "Voltaje de carga del alternador" },
            { id: "m16", label: "Estado de la marcha (arranque rápido)" },
            { id: "m17", label: "Presión de combustible" },
            { id: "m18", label: "Fugas de vacío" },
            { id: "m19", label: "Estado del sensor MAF/MAP" },
            { id: "m20", label: "Temperatura de operación estable" },
            { id: "m21", label: "Ausencia de códigos de error (Check Engine)" },
            { id: "m22", label: "Estado del tapón de aceite (sin lodo blanco)" },
            { id: "m23", label: "Ruidos en la bomba de agua" },
            { id: "m24", label: "Estado del compresor de A/C" },
            { id: "m25", label: "Estado del ventilador del radiador" },
            { id: "m26", label: "Integridad de la computadora (ECU)" },
            { id: "m27", label: "Estado del cárter (sin golpes)" },
            { id: "m28", label: "Mangueras de admisión sin grietas" },
            { id: "m29", label: "Nivel de líquido de dirección hidráulica" },
            { id: "m30", label: "Limpieza general del vano motor" }
        ]
    },
    {
        id: "transmision",
        label: "Transmisión",
        items: [
            { id: "t1", label: "Suavidad al engranar velocidades" },
            { id: "t2", label: "Ausencia de ruidos (zumbidos) en marcha" },
            { id: "t3", label: "Estado del pedal de embrague (altura/dureza)" },
            { id: "t4", label: "Corte del embrague (que no patine)" },
            { id: "t5", label: "Nivel de aceite de transmisión" },
            { id: "t6", label: "Estado de los cubrepolvos de flechas" },
            { id: "t7", label: "Ausencia de vibraciones al acelerar" },
            { id: "t8", label: "Funcionamiento de la reversa" },
            { id: "t9", label: "Estado de los sincronizadores" },
            { id: "t10", label: "Fugas de aceite en la caja" },
            { id: "t11", label: "Estado del diferencial (sin ruidos)" },
            { id: "t12", label: "Respuesta del Kick-down (en automáticos)" },
            { id: "t13", label: "Cambios sin \"patadas\" (en automáticos)" },
            { id: "t14", label: "Funcionamiento del modo manual/Sport" },
            { id: "t15", label: "Estado de la palanca (sin juego excesivo)" },
            { id: "t16", label: "Soportes de transmisión" },
            { id: "t17", label: "Integridad del cardán (si aplica)" },
            { id: "t18", label: "Estado de las juntas homocinéticas" },
            { id: "t19", label: "Funcionamiento del Overdrive" },
            { id: "t20", label: "Temperatura de la transmisión" },
            { id: "t21", label: "Ausencia de códigos de error de caja" },
            { id: "t22", label: "Líquido de transmisión sin olor a quemado" },
            { id: "t23", label: "Prueba de calado (en automáticos)" },
            { id: "t24", label: "Funcionamiento del parking" },
            { id: "t25", label: "Estado de los cables/varillaje de cambios" },
            { id: "t26", label: "Ausencia de fugas en cilindro maestro de embrague" },
            { id: "t27", label: "Respuesta en pendientes" },
            { id: "t28", label: "Estabilidad de RPM en cambios" },
            { id: "t29", label: "Integridad de la carcasa de la caja" },
            { id: "t30", label: "Fluidez de la tracción 4x4 (si aplica)" }
        ]
    },
    {
        id: "suspension",
        label: "Suspensión y Frenos",
        items: [
            { id: "s1", label: "Estado de los amortiguadores delanteros (sin fugas)" },
            { id: "s2", label: "Estado de los amortiguadores traseros" },
            { id: "s3", label: "Bujes de horquillas" },
            { id: "s4", label: "Rótulas (sin juego)" },
            { id: "s5", label: "Terminales de dirección" },
            { id: "s6", label: "Bieletas de barra estabilizadora" },
            { id: "s7", label: "Gomas de barra estabilizadora" },
            { id: "s8", label: "Estado de los resortes (sin grietas)" },
            { id: "s9", label: "Alineación del vehículo (no se jala)" },
            { id: "s10", label: "Estabilidad en curvas" },
            { id: "s11", label: "Nivel de líquido de frenos" },
            { id: "s12", label: "Estado de balatas delanteras (vida útil)" },
            { id: "s13", label: "Estado de balatas traseras" },
            { id: "s14", label: "Estado de los discos de freno (sin ceja)" },
            { id: "s15", label: "Frenado sin vibraciones (discos no alabeados)" },
            { id: "s16", label: "Funcionamiento del freno de mano" },
            { id: "s17", label: "Estado de las mangueras de freno" },
            { id: "s18", label: "Funcionamiento del sistema ABS" },
            { id: "s19", label: "Servofreno (Booster) sin fugas de vacío" },
            { id: "s20", label: "Rodamientos de rueda (sin ruidos)" },
            { id: "s21", label: "Estado de las llantas delanteras (dibujo)" },
            { id: "s22", label: "Estado de las llantas traseras" },
            { id: "s23", label: "Desgaste uniforme de neumáticos" },
            { id: "s24", label: "Estado de los rines (sin dobleces)" },
            { id: "s25", label: "Presión de aire correcta" },
            { id: "s26", label: "Llanta de refacción y herramienta" },
            { id: "s27", label: "Caja de dirección (sin fugas)" },
            { id: "s28", label: "Bomba de asistencia sin ruidos" },
            { id: "s29", label: "Ausencia de ruidos metálicos en baches" },
            { id: "s30", label: "Respuesta del pedal de freno (firmeza)" }
        ]
    },
    {
        id: "carroceria",
        label: "Carrocería y Estética",
        items: [
            { id: "c1", label: "Pintura original en cofre" },
            { id: "c2", label: "Pintura original en toldo" },
            { id: "c3", label: "Pintura original en cajuela" },
            { id: "c4", label: "Ausencia de golpes estructurales en chasis" },
            { id: "c5", label: "Alineación de puertas y salpicaderas" },
            { id: "c6", label: "Estado de los cristales (sin fisuras)" },
            { id: "c7", label: "Funcionamiento de elevadores eléctricos" },
            { id: "c8", label: "Estado de los espejos laterales" },
            { id: "c9", label: "Funcionamiento de quemacocos" },
            { id: "c10", label: "Cierre centralizado de seguros" },
            { id: "c11", label: "Estado de las calaveras" },
            { id: "c12", label: "Estado de los faros (no opacos)" },
            { id: "c13", label: "Funcionamiento de luces altas/bajas" },
            { id: "c14", label: "Luces de giro y preventivas" },
            { id: "c15", label: "Luz de freno y reversa" },
            { id: "c16", label: "Estado de la tapicería de asientos" },
            { id: "c17", label: "Limpieza del cielo/toldo interior" },
            { id: "c18", label: "Estado del tablero (sin grietas)" },
            { id: "c19", label: "Alfombra sin humedad/olores" },
            { id: "c20", label: "Funcionamiento del aire acondicionado (frío)" },
            { id: "c21", label: "Funcionamiento de la calefacción" },
            { id: "c22", label: "Estado de los cinturones de seguridad" },
            { id: "c23", label: "Pantalla e infoentretenimiento" },
            { id: "c24", label: "Sistema de sonido/bocinas" },
            { id: "c25", label: "Mandos al volante" },
            { id: "c26", label: "Limpiaparabrisas (estado y motor)" },
            { id: "c27", label: "Apertura remota de cajuela/gasolina" },
            { id: "c28", label: "Estado de los plásticos exteriores" },
            { id: "c29", label: "Presencia de todos los emblemas" },
            { id: "c30", label: "Estado de las chapas y llaves" }
        ]
    },
    {
        id: "legal",
        label: "Legal y Documentación",
        items: [
            { id: "l1", label: "Factura original o secuencia completa" },
            { id: "l2", label: "Consulta de REPUVE (sin reporte de robo)" },
            { id: "l3", label: "Validación de número de serie (VIN) físico vs documento" },
            { id: "l4", label: "Número de motor coincidente" },
            { id: "l5", label: "Placas vigentes" },
            { id: "l6", label: "Última verificación vehicular aprobada" },
            { id: "l7", label: "Historial de tenencias (últimos 5 años)" },
            { id: "l8", label: "Ausencia de multas de tránsito pendientes" },
            { id: "l9", label: "Tarjeta de circulación vigente" },
            { id: "l10", label: "Comprobante de baja de placas (si aplica)" },
            { id: "l11", label: "Seguro vigente (opcional)" },
            { id: "l12", label: "Manuales de propietario" },
            { id: "l13", label: "Carnet de servicios sellado" },
            { id: "l14", label: "Duplicado de llaves" },
            { id: "l15", label: "Validación de procedencia (agencia/lote)" },
            { id: "l16", label: "Consulta de adeudos de fotomultas" },
            { id: "l17", label: "Estado de propiedad (sin gravamen)" },
            { id: "l18", label: "RFC del vendedor validado" },
            { id: "l19", label: "Identificación oficial del dueño anterior" },
            { id: "l20", label: "Contrato de compra-venta listo" },
            { id: "l21", label: "Validación de kilometraje (coherencia con servicios)" },
            { id: "l22", label: "Verificación de reporte de recuperación de seguro" },
            { id: "l23", label: "Dictamen de peritaje previo (si hay)" },
            { id: "l24", label: "Pago de derechos de control vehicular" },
            { id: "l25", label: "Carta responsiva" },
            { id: "l26", label: "Folios de facturación ante el SAT" },
            { id: "l27", label: "Historial de propietarios anteriores" },
            { id: "l28", label: "Cotejo de datos en portal estatal" },
            { id: "l29", label: "Verificación de sellos de seguridad en facturas" },
            { id: "l30", label: "Firma de documentos legales completa" }
        ]
    }
];
